### ISSUE TITLE
Better plotting with ImPlot

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgImGui#22]
Hi Robert,

this is not really an issue, since VsgImgui works well. It's plot capabilities are very limited yet. You cannot define axis labels for example. There is a companion project called ImPlot, which can be integrated into ImGui/VSGImgui. Actually I needed gui-charts in project::chrono, so I made a modified version of the VsgImgui library.
![ImPlot_Example](https://user-images.githubusercontent.com/31243285/198564072-c9ebfdf6-40e9-4ab6-981d-130d8829af1a.png)
I think some users would like this additional feature. What is your opinion?

Best

Rainer

**Comment by robertosfield** [comment]
I am not familiar with ImPlot so can't provide any guidance on it until I've learned more.  As I'm deep in a code review of the core VSG in prep for 1.0 I'll need to handle this after the release.

If you have a modified vsgImGui then could you share this so I can review it there.

**Comment by rainergericke** [comment]
Here is it:

**Comment by rainergericke** [comment]
There is a PR.
