### ISSUE TITLE
Missing up to date tag for building stable releases

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgImGui#29]
To build stable binary packages on Linux (openSUSE) from this project, a tag is required which matches the current vsg API. The current [vsgImGui-0.0.0](https://github.com/vsg-dev/vsgImGui/releases/tag/vsgImGui-0.0.0) does not match the current vsg API.

**Comment by robertosfield** [comment]
? We don't have a stable release for vsgImGui before it needs more work before it can be considered stable.
