### ISSUE TITLE
Render to texture / without a vsg::Window (vsgvr integration)

### ISSUE THREAD

**Issue by geefr** [vsg-dev/vsgImGui#33]
(I hope I haven't missed something obvious here)

I think we need some more flexibility around rendering to texture or similar - Specifically I've experimented with vsgvr rendering imgui to an in-world quad.
* At first I'm using the concept of 'composition layers', which are similar to Windows (composition performed by the vr runtime, but ignoring depth buffers)
* Rendering to a vsg::Image within the scene would be an alternate approach for in-scene UI

The main issue I faced was that I don't have vsg::Window, so for the prototype I forked vsgImGui::RenderImGui:
* https://github.com/geefr/vsgvr/blob/vsgimgui-prototype/vsgvr/src/vsgvr/imgui/RenderImGui.cpp

My questions for vsgImGui are:
* Would it make sense to update vsgImGui::RenderImGui, to allow rendering without a Window?
* If so, do my prototype changes seem sensible, obviously if the vsgvr-specific types weren't used
* For desktop or vr applications, is the RenderGraph the best approach for rendering to a vsg::Image?
  * I'm sure if vsgImGui supports that, then I can apply that image as needed

I'm happy to go whichever route is best, and if needed can have a separate imgui integration for the vr integration. Certainly when it comes to the question of input I'd need some extra mapping to take scene intersections through to input anyway.

**Comment by robertosfield** [comment]
Making things more flexible to handle your usage case sounds sensible.  Do
you have a specific commit to vsgImGui that adds the render to texture
support?  Without this I'll need to just compare vsgImGui originals against
yours, but this is prone to errors if vsgImGui has changed since you
branched it.

**Comment by geefr** [comment]
Nothing like that yet, just a quick hack to see how it could work and explore approaches. The linked prototype is the only change so far - It couldn't be used directly as it's bound to the vsgvr API, and I think I'll need a second change for rendering UI within the scene.

I'm happy to dig deeper on this one, and get a PR put together. Rendering to images / textured quads seems to be a recurring theme, and this is a good test case for more interactive vr apps.

**Comment by geefr** [comment]
Think I've got the vsgImGui side changes for this, here's a PR: https://github.com/vsg-dev/vsgImGui/pull/36

On the VR side I haven't fully tested things, but rendering a texture to an in-world quad is definitely needed.

No update on the input side of things, but I don't see anything that would prevent mapping some virtual intersection through to a window mouse event / similar yet.
