### ISSUE TITLE
ImGui assertion failure when pressing any key within an input box.

### ISSUE THREAD

**Issue by kannode** [vsg-dev/vsgImGui#34]
Some things, such as input handling, have changed in ImGui. This issue tracks the problem where on Mac and Windows, ImGui results in an assertion failure. Perhaps this is an excellent incentive to move to the latest version of ImGui while fixing the assertion issue.

**Comment by robertosfield** [comment]
On Wed, 11 Jan 2023 at 11:32, Suresh Kannan ***@***.***>
wrote:

> Some things, such as input handling, have changed in ImGui. This issue
> tracks the problem where on Mac and Windows, ImGui results in an assertion
> failure. Perhaps this is an excellent incentive to move to the latest
> version of ImGui while fixing the assertion issue.
>
> Could you provide a stack trace and details of the assertion failure?

Have you tried Unix?  I have Linux systems here so if a failure occurs
under Linux it'll help me investigate.

**Comment by kannode** [comment]
No issue on Linux, only on Mac and Windows. Instead of figuring out the old Imgui Input system, I plan to figure out the new one that uses AddKeyEvent API that matches VSG better.

**Comment by robertosfield** [comment]
I haven't looked at the new ImGui API yet, currently busy trying to figure out Qt oddities which will keep me busy.  If you have suggestions on the ImGui front let me know.  I'm happy to see vsgImGui evolve to keep up with ImGui.

**Comment by kannode** [comment]
I closed this one as I had raised and it seems to have been merged in.
