### ISSUE TITLE
Build failure on vsgimgui_example: undefined reference to `ImPlot::ShowDemoWindow(bool*)'

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgImGui#40]
The vsgimgui example from the vsgExample project fails to build with MinGW:

```sh
[  138s] /usr/bin/i686-w64-mingw32-g++ -O2 -g -pipe -Wall -fexceptions --param=ssp-buffer-size=4 -mms-bitfields -O2 -g -DNDEBUG -Wl,--exclude-libs=libintl.a -Wl,--exclude-libs=libiconv.a -Wl,--no-keep-memory -fstack-protector -Wl,--whole-archive CMakeFiles/vsgimgui_example.dir/objects.a -Wl,--no-whole-archive -o ../../../bin/vsgimgui_example.exe -Wl,--out-implib,../../../lib/libvsgimgui_example.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/vsgimgui_example.dir/linklibs.rsp
[  138s] /usr/lib64/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld: CMakeFiles/vsgimgui_example.dir/objects.a(vsgimgui_example.cpp.obj): in function `ZN14MyGuiComponentclEv':
[  138s] /home/abuild/rpmbuild/BUILD/vsgExamples-0.0.0+20230116+git.1f0d5ac/examples/ui/vsgimgui_example/vsgimgui_example.cpp:84: undefined reference to `ImPlot::ShowDemoWindow(bool*)'
[  138s] collect2: error: ld returned 1 exit status
```
The shared vsgImGui library is build from git commit https://github.com/vsg-dev/vsgImGui/commit/febfa8353de0ae1243709e29fe65dbbce8c594fb.

**Comment by rhabacker** [comment]
> Have you seen the same build error occur on any other build/OS combinations?

This problem occurs on Windows (32bit and 64bit) when vsgImGui is built as a shared library, caused by a non-functioning symbol export of the corresponding symbols in vsgImGui. It will also occur with msvc when vsgImGui is built as a shared library.

> Have you made any progress on this issue ?

For a solution, the question needs to be answered whether methods of class `ImPlot` should be exported from vsgImGui or not. If yes, then this needs to be fixed accordingly in vsgImGui, otherwise the related calls need to be removed from vsgExamples.

**Comment by robertosfield** [comment]
Looking at imgui.h and implot.h, they uses IMGUI_API and IMPLOT_API #define respectively, for imgui.h it looks to pull in the IMGU_API #define from imconfig.h, but I can't see an equivilant form implot.h.

I don't know ImPlot, my only experience with has been compiling, testing and merging the PRs.  I don't know if there is a standard scheme for dealing with the IMPLOT_API import/export specification but this is avenue I'd look at.  Would appreciate others chipping in as I'm new to ImPlot.

**Comment by rhabacker** [comment]
> Looking at imgui.h and implot.h, they uses IMGUI_API and IMPLOT_API #define respectively, for imgui.h it looks to pull in the IMGU_API #define from imconfig.h, but I can't see an equivilant form implot.h.

This is differently solved. `Imgui.h` contains 

```cpp
#ifdef IMGUI_USER_CONFIG
#include IMGUI_USER_CONFIG
#endif
```
which is set to `-DIMGUI_USER_CONFIG="<vsgImGui/Export.h>` by cmake. In that file the export decorations are located.

ImPlot does not have such a thing, it simply expects `IMPLOT_API` to be set accordingly. 

Since `Implot.h` contains `Imgui.h`, the problem can be solved by adding the following line after https://github.com/vsg-dev/vsgImGui/blob/0259096f5e0e502d466fb74a34f22653aec26966/include/vsgImGui/Export.h#L38.
```cpp
#define IMPLOT_API VSGIMGUI_DECLSPEC
```

**Comment by robertosfield** [comment]
Thanks for spotting this very simple solution.  Can't believe I didn't spot
this :-)
