### ISSUE TITLE
Missing header during vsgFramework build 

### ISSUE THREAD

**Issue by rserban** [vsg-dev/vsgImGui#41]
When building vsgImGui as part of vsgFramework (https://github.com/vsg-dev/vsgFramework), the `imconfig.h` header is not found.  It is present under `src/imgui/` but that path is not searched. I suppose one fix would be to copy `imconfig.h` to `include/vsgImGui/` (not sure if that's the best idea though).

**Comment by robertosfield** [comment]
Fixed with #43.
