### ISSUE TITLE
Build failure with mingw32 g++ 12 compiler: invalid 'static_cast' from type 'VkDescriptorSet' {aka 'long long unsigned int'} to type 'ImTextureID' {aka 'void*'}

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgImGui#49]
With commit https://github.com/vsg-dev/vsgImGui/commit/78c06ee3d2bb21b3cc9797d1b874f7c3999cdb6c building of vsgImGui fails with mingw g++ 12 compiler as shown below:

```sh 
   77s] cd /home/abuild/rpmbuild/BUILD/vsgImGui-0.0.0+20230407+git.78c06ee/build/src && /usr/bin/i686-w64-mingw32-g++ -DIMGUI_USER_CONFIG="<vsgImGui/Export.h>" -DVSG_SHARED_LIBRARY -DvsgImGui_EXPORTS @CMakeFiles/vsgImGui.dir/includes_CXX.rsp -O2 -g -pipe -Wall -fexceptions --param=ssp-buffer-size=4 -mms-bitfields -O2 -g -DNDEBUG -Wall -Wparentheses -Wno-long-long -Wno-import -Wreturn-type -Wmissing-braces -Wunknown-pragmas -Wmaybe-uninitialized -Wshadow -Wunused -Wno-misleading-indentation -Wextra -std=gnu++17 -MD -MT src/CMakeFiles/vsgImGui.dir/vsgImGui/Texture.cpp.obj -MF CMakeFiles/vsgImGui.dir/vsgImGui/Texture.cpp.obj.d -o CMakeFiles/vsgImGui.dir/vsgImGui/Texture.cpp.obj -c /home/abuild/rpmbuild/BUILD/vsgImGui-0.0.0+20230407+git.78c06ee/src/vsgImGui/Texture.cpp
[   77s] /home/abuild/rpmbuild/BUILD/vsgImGui-0.0.0+20230407+git.78c06ee/src/vsgImGui/Texture.cpp: In member function 'void* vsgImGui::Texture::id(uint32_t) const':
[   77s] /home/abuild/rpmbuild/BUILD/vsgImGui-0.0.0+20230407+git.78c06ee/src/vsgImGui/Texture.cpp:78:28: error: invalid 'static_cast' from type 'VkDescriptorSet' {aka 'long long unsigned int'} to type 'ImTextureID' {aka 'void*'}
[   77s]    78 |     return descriptorSet ? static_cast<ImTextureID>(descriptorSet->vk(deviceID)) : ImTextureID{};
[   77s]       |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  
 77s] make[2]: *** [src/CMakeFiles/vsgImGui.dir/build.make:110: src/CMakeFiles/vsgImGui.dir/vsgImGui/Texture.cpp.obj] Error ```
[_log.txt](https://github.com/vsg-dev/vsgImGui/files/11200037/_log.txt)

**Comment by robertosfield** [comment]
I can't see how this commit would affect the type cast.  Did it actually compile prior to this commit?

I don't have mingw so can't test out any possible fixes.  The commit doesn't look to have any clues as to what it might cause an issue so I suspect it's an issue that predates this commit.  @rhabacker do you have any ideas of how to resolve this issue?

**Comment by rhabacker** [comment]
> I can't see how this commit would affect the type cast. 

I recognized this issue when compiling the the mentioned commit.

> Did it actually compile prior to this commit?

I did run `git bisect` to get the first broken commit and got https://github.com/vsg-dev/vsgImGui/commit/70ff58f4e3d47afe17bb067318f3c62dea69d8d5

> I don't have mingw so can't test out any possible fixes. The commit doesn't look to have any clues as to what it might cause an issue so I suspect it's an issue that predates this commit. 

I agree, see above

@rhabacker do you have any ideas of how to resolve this issue?

I compared the build with mingw64 and see that this is a 32bit problem, since in the cast 

``` 
Type 'VkDescriptorSet' {aka 'long long unsigned int'} to type 'ImTextureID' {aka 'void*'}
```
the type `ImTextureID` is `void*` and therefore a 32bit value, while `VkDescriptorSet` is a 64 bit type. Bits would be lost in the conversion, hence the message. 

The target type void* is not cross-platform here.

**Comment by robertosfield** [comment]
This sounds like a ImGui problem then. I wonder if the VkDescriptorSet will
just use the lower 32bits...

**Comment by rhabacker** [comment]
ImGui provides a way to override the built-in type for `ImTextureID`, see github.com/ocornut/imgui/blob/f3f6295d532b98e322691afb8ef418209d963786/imgui.h#L212. That might be a possibility as well.

**Comment by robertosfield** [comment]
I have just been experimenting with setting a #define ImTextureID in include/vsgImGui/Export.h but haven't yet got it to work even on my 64bit system.

**Comment by rhabacker** [comment]
I got success by adding the following lines to RenderImGui.h

```
+ typedef VkDescriptorSet ImTextureID;
+ #define ImTextureID ImTextureID
  #include <vsgImGui/imgui.h>
```

**Comment by rhabacker** [comment]
> I have done something similar, could you try ImTextureIDFix branch I've just checked in:

Works on linux x86_64 and mingw32 and mingw64 - thanks for fixing.

**Comment by robertosfield** [comment]
Thanks for the testing.  I have merged the branch with vsgImGui master.
