### ISSUE TITLE
Release version is missing for conan-integration

### ISSUE THREAD

**Issue by psyinf** [vsg-dev/vsgImGui#54]
Hi Robert, 

Could you please create a release or at least a (1.0.0?)-tag for vsgImGui that preferably works with vsg-1.0.3, so I can create the conan-integration for this component? 
Apart from this it would be really nice if the submodules referenced could point to releases/tags. This make managing them less awkward and doesn't give that "random version"-taste.

A little background: conan bases its dependencies on tar-balls/zips in conjunction with the specific sha256 to be used as a version.

**Comment by robertosfield** [comment]
Would it need to be 1.0.s or could it be a 0.x.x release?

vsgImGui pulls in ImGui and ImPlot as giit submodules, is his compatible?

**Comment by psyinf** [comment]
Hi Robert, 
it can be any release version. The submodules are ok, but it would be much better if they'd reference a tag or branch. 
I've already moved towards vsg 1.0.5 for testing. So maybe we could stick to 1.0.5 and use the current master as a "stable" reference.

Cheers
Sebastian

**Comment by robertosfield** [comment]
Closing as we now have a 0.1.0 release:

https://github.com/vsg-dev/vsgImGui/releases/tag/v0.1.0
