### ISSUE TITLE
Mouse double click is not working

### ISSUE THREAD

**Issue by aiekick** [vsg-dev/vsgImGui#55]
Hello,

im under win10 with the current version of vsg and vsgImGui (pulled yseterday)

the mouse double click is not working. (only tested on window)
Its like some frame ar jummped or something

Ater some hours of search i found the solution. and is in vsg :

the fix is in Win32_WIndow.cpp :

at line 584
```cpp
    case WM_LBUTTONDBLCLK:
    case WM_MBUTTONDBLCLK:
    case WM_RBUTTONDBLCLK: {
        int32_t mx = GET_X_LPARAM(lParam);
        int32_t my = GET_Y_LPARAM(lParam);
        bufferedEvents.emplace_back(vsg::ButtonPressEvent::create(this, event_time, mx, my, getButtonMask(wParam), getButtonDownEventDetail(msg)));
    }
```

like that on the second fast click, the event count is increased of 1 in ImGui. 
And when he goes to 2, the event DoubleClick is generated in ImGui

**Comment by robertosfield** [comment]
From reading just your report I can't see what you've modified or how your intended change effects things.

Could you generate a PR that illustrates your proposed change.

**Comment by aiekick** [comment]
sure i will

**Comment by robertosfield** [comment]
Just following up @aiekick, I don't recall a PR, is this still pending?

**Comment by aiekick** [comment]
Hello,

i though i created a PR, but its seems not. 
btw i not working any more on vsg, prefering to create my own vulkan framework.

btw you have my solution.
