### ISSUE TITLE
Example link in README.md is broken

### ISSUE THREAD

**Issue by evilenzo** [vsg-dev/vsgImGui#59]
Link for example leads to https://github.com/vsg-dev/vsgExamples/tree/master/examples/ui/vsgimgui but it's broken. Actual link is https://github.com/vsg-dev/vsgExamples/tree/master/examples/ui/vsgimgui_example

**Comment by robertosfield** [comment]
Thanks for reporting the issue, now fixed: e0f9132e4a92895080656b0eea533b6eb9a00e64
