### ISSUE TITLE
imgui API change

### ISSUE THREAD

**Issue by waywardmonkeys** [vsg-dev/vsgImGui#66]
In imgui 1.90.3, there was an API change for the Vulkan integration:

https://github.com/ocornut/imgui/commit/f80e65a406885beedf68856057b278343d5c1407#diff-18750075cb03187e13c77772fdeedf0c4a573c755a67b9d309f7c773023e6f0c

(That points to the example in the commit that did the change.)

If you want to keep compatibility with older versions, you could probably protect the old style of code with something like:

```
#if IMGUI_VERSION_NUM < 19030
```

**Comment by waywardmonkeys** [comment]
(I don't use veg, I just found this when trying to update the version of `imgui` in `vcpkg`.)

**Comment by robertosfield** [comment]
vsgImGui pulls in it's own version of ImGui as a submodule via a specific tag (current 1.90.1 #64) so should be insulated from changes to ImGui.  I am not familiar with vpkg integration of imgui or vsgImGui so could you what issues you saw as I would have thought that vsgImGui should be work independently from imgui thank to pulling it via a submodule.

**Comment by waywardmonkeys** [comment]
As part of their policy, they de-vendor things as seen here: https://github.com/microsoft/vcpkg/tree/6978381401d33a5ad6a3385895d12e383083712a/ports/vsgimgui

So this can be patched there, but figured best if it happens here since it would be needed at some point anyway.

**Comment by robertosfield** [comment]
Thanks for the link.  All those hacks to work the "vcpkg" way is painful to see.  Undoing all the things that vsgImGui does to ensure a stable experience across all platforms for vsgImGui users - the break you are suggesting is down to vcpkg deciding on a newer version of imgui than vsgImGui is currently set up for.  It builds against 1.90.1 so it's not like we're particularly behind the curve.

**Comment by robertosfield** [comment]
As prep for a 0.3.0 release of vsgImGui I have updated ImGui to 1.90.5 and made the required changes to vsgImGui: 0196a2444ed207e8d3a87eb14103cac5c35de7e2
