### ISSUE TITLE
link error by vs2022 LNK2019

### ISSUE THREAD

**Issue by x1244** [vsg-dev/vsgImGui#67]
When I build vsgExample/ui/vsgimgui_example, I got the error

```
error: vsgImGui.lib(implot.obj) : error LNK2019: 无法解析的外部符号 "unsigned int __cdecl ImGui::GetColorU32(unsigned int)" (?GetColorU32@ImGui@@YAII@Z)，函数 "bool __cdecl ImPlot::ShowLegendEntries(struct ImPlotItemGroup &,struct ImRect const &,bool,struct ImVec2 const &,struct ImVec2 const &,bool,struct ImDrawList &)" (?ShowLegendEntries@ImPlot@@YA_NAEAUImPlotItemGroup@@AEBUImRect@@_NAEBUImVec2@@32AEAUImDrawList@@@Z) 中引用了该符号
build\windows\x64\release\imgui.exe : fatal error LNK1120: 1 个无法解析的外部命令
```

Platform：win10 vs2022
vsgImGui commit 0bbb45a68ba6b699b8f418a585f45363be1540c1 tag v0.3.0
vsgExample commit 9d3ae99f4362d271d3a16e3f4ad50a627ada6667  tag v1.1.4
vsg commit 967e6327790c8553e806023de03c0b11ec192db4 tag v1.1.4

**Comment by robertosfield** [comment]
I haven't seen this issue myself under Linux or Windows, and others have been using vsgImGui under Windows fine so I don't know why you've had issues while others haven't,

I've pulled in the latest ImGui v1.90.8 today and tagged a vsgImGui-0.4.0 release for this.  Could you try updating to v-0.4.0 or vsgImGui master to see if the issue is fixed.

**Comment by x1244** [comment]
when use the cmake command with the arg ‘-A x64’，got the error.
```
cmake -G "Visual Studio 17 2022" -A x64 
```
When not use the arg '-A x64', it pass the link.
```
cmake -G "Visual Studio 17 2022" 
```

**Comment by x1244** [comment]
I think the problem has been solved.

**Comment by x1244** [comment]
Use `cmake -G "Visual Studio 17 2022" ` to generate vs project, then build the vsgimgui project, and install it.
Rebuild vsgimgui_example, no link error now.
