### ISSUE TITLE
There is no 'ImGui::EndFrame();' in 'RenderImGui::renderComponents'

### ISSUE THREAD

**Issue by karolmateusznowak** [vsg-dev/vsgImGui#7]
ImGui::NewFrame() should be ended with ImGui::EndFrame() before ImGui::Render()

**Comment by robertosfield** [comment]
I have add an ImGui::EndFrame() call in before the ImGui::Render().  I don't see any change in behaviour, but it seems to make sense to do this.  1ed2aa693080b42a3c3290cdca0f88ea3a2e7944
